//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KatBarberShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.TheEnd = new HashSet<TheEnd>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> ContactsID { get; set; }
        public Nullable<int> PriceListID { get; set; }
        public Nullable<int> StocksID { get; set; }
    
        public virtual Contacts Contacts { get; set; }
        public virtual PriceList PriceList { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual ICollection<TheEnd> TheEnd { get; set; }
    }
}
