//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KatBarberShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public Stock()
        {
            this.Clients = new HashSet<Clients>();
        }
    
        public int Id { get; set; }
        public string Students { get; set; }
        public string Sun_And_Father { get; set; }
        public string Day_Nice { get; set; }
        public string One_One { get; set; }
    
        public virtual ICollection<Clients> Clients { get; set; }
    }
}
