//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KatBarberShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public Worker()
        {
            this.TheEnd = new HashSet<TheEnd>();
        }
    
        public int Number { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public System.DateTime Data { get; set; }
        public string Paul { get; set; }
    
        public virtual ICollection<TheEnd> TheEnd { get; set; }
    }
}
